#!/usr/bin/env bash
# scripts/build-index.sh
# Regenerates the section-index portion of DESIGN_TREE.md by extracting
# `^## ` headings from each bible. Leaves the decision-tree prose at the
# top of DESIGN_TREE.md untouched; rewrites only the index tables at the
# bottom.
#
# Usage: bash scripts/build-index.sh
# Output: updated DESIGN_TREE.md with current section headings from bibles.

set -euo pipefail

cd "$(dirname "$0")/.."

MARKER_START="<!-- BIBLE_INDEX_START -->"
MARKER_END="<!-- BIBLE_INDEX_END -->"

# Build the index markdown block
build_block() {
  echo "$MARKER_START"
  echo ""
  echo "<!-- Auto-generated by scripts/build-index.sh. Do not edit by hand. -->"
  echo ""

  for bible in WEB MOBILE WEARABLE XR ICONS; do
    file="bibles/${bible}.md"
    [ ! -f "$file" ] || [ ! -s "$file" ] && continue

    count=$(grep -c '^## ' "$file" || echo 0)
    echo "### ${bible}.md — ${count} sections"
    echo ""
    echo "| Section | Title |"
    echo "|---------|-------|"

    # Extract `## X. Title` → table row
    grep -nE '^## ' "$file" | sed -E 's/^([0-9]+):## (.*)$/| L\1 | \2 |/'
    echo ""
  done

  echo "$MARKER_END"
}

# Check if DESIGN_TREE.md has the markers
if ! grep -q "$MARKER_START" DESIGN_TREE.md; then
  echo "ℹ  DESIGN_TREE.md has no index markers yet. Appending index block at the end."
  {
    echo ""
    echo "---"
    echo ""
    echo "## Bible section index (auto-generated)"
    echo ""
    build_block
  } >> DESIGN_TREE.md
  echo "✓ Index block appended."
  exit 0
fi

# Replace between markers using awk
tmpfile=$(mktemp)
awk -v start="$MARKER_START" -v end="$MARKER_END" \
    -v block_file="/tmp/bible-index-block.$$" \
    '
    BEGIN { printing = 1 }
    $0 ~ start { printing = 0; system("cat " block_file); next }
    $0 ~ end { printing = 1; next }
    printing == 1 { print }
    ' DESIGN_TREE.md > "$tmpfile" || { rm -f "$tmpfile" /tmp/bible-index-block.$$; exit 1; }

# Build the fresh block
build_block > "/tmp/bible-index-block.$$"

# Re-run the substitution (simpler approach: split + replace + stitch)
awk -v start="$MARKER_START" -v end="$MARKER_END" \
    '
    BEGIN { skip = 0; printed_replacement = 0 }
    {
      if ($0 ~ start) {
        skip = 1
        print
        while ((getline line < "/tmp/bible-index-block.'$$'") > 0) {
          if (line != start && line != end) print line
        }
        close("/tmp/bible-index-block.'$$'")
        next
      }
      if ($0 ~ end) {
        skip = 0
        print
        next
      }
      if (skip == 0) print
    }
    ' DESIGN_TREE.md > "$tmpfile"

mv "$tmpfile" DESIGN_TREE.md
rm -f "/tmp/bible-index-block.$$"

total=$(for b in WEB MOBILE WEARABLE XR ICONS; do grep -c '^## ' "bibles/${b}.md" 2>/dev/null || echo 0; done | awk '{s+=$1} END{print s}')
echo "✓ DESIGN_TREE.md index rebuilt — ${total} sections across 5 bibles."
